update deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -5,6 +5,20 @@
 
 echo "INFO: Welcome to VirtualBox Power Driver for MAAS (vboxpower)"
 
+which python3 &> /dev/null
+
+if [ $? -ne 0 ]; then
+    echo "ERROR: Python3 is not installed."
+    exit 1
+fi
+
+which pip3 &> /dev/null
+
+if [ $? -ne 0 ]; then
+    echo "ERROR: Pip3 is not installed."
+    exit 1
+fi
+
 which virtualbox &> /dev/null
 
 if [ $? -ne 0 ]; then
@@ -14,7 +28,7 @@ else
     echo "INFO: VirtualBox is installed on the system."
 fi
 
-pip freeze | grep vboxapi &> /dev/null
+pip3 freeze | grep vboxapi &> /dev/null
 
 if [ $? -ne 0 ]; then
     echo "ERROR: VirtualBox SDK is not installed."
@@ -23,7 +37,7 @@ else
     echo "INFO: VirtualBox SDK is installed on the system."
 fi
 
-pip install -r requirements.txt &> /dev/null
+pip3 install -r requirements.txt &> /dev/null
 
 if [ $? -ne 0 ]; then
     echo "ERROR: Cannot install the required packages."
@@ -37,6 +51,6 @@ cp vboxpower.service /etc/systemd/system/vboxpower.service
 mkdir -p /opt/maas/vboxpower
 cp vboxpower.py /opt/maas/vboxpower/vboxpower.py
 
-echo "INFO: Starting vboxpower systemd service."
+echo "INFO: Starting vboxpower service."
 
 systemctl enable --now vboxpower.service
